[tool.poetry]
name = "nixops_hcloud"
version = "0.1.0"
description = "NixOps Hetzner Cloud plugin"
authors = ["lukebfox <mail@lukebentleyfox.net>"]
license = "LGPL-3.0-only"
include = [ "nixops_hcloud/nix/*.nix" ]

[tool.poetry.dependencies]
python = "~3.7"
hcloud = "1.6.3"
nixops = {git = "https://github.com/NixOS/nixops.git", rev = "master"}
typing-extensions = "^3.7.4"
nixos-modules-contrib = {git = "https://github.com/nix-community/nixos-modules-contrib.git", rev = "master"}

[tool.poetry.dev-dependencies]
nose = "^1.3.7"
mypy = "^0.770"
black = "^19.10b0"
flake8 = "^3.8.2"
jedi = "0.15.2"

[tool.poetry.plugins."nixops"]
hcloud = "nixops_hcloud.plugin"

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
