[tool.poetry]
name = "nixops_hetznercloud"
version = "0.1.0"
description = "NixOps Hetzner Cloud plugin"
authors = ["lukebfox <mail@lukebentleyfox.net>"]
license = "LGPL-3.0-only"
include = [ "nixops_hetznercloud/nix/*.nix" ]

[tool.poetry.dependencies]
python = "~3.8"
hcloud = "1.8.1"
nixops = {path = "../nixops"}
#nixops = {git = "https://github.com/lukebfox/nixops.git", rev = "fix-diff-engine"}
typing-extensions = "^3.7.4"
nixos-modules-contrib = {git = "https://github.com/nix-community/nixos-modules-contrib.git", rev = "master"}

[tool.poetry.dev-dependencies]
nose = "^1.3.7"
mypy = "^0.770"
black = "^19.10b0"
flake8 = "^3.8.2"

[tool.poetry.plugins."nixops"]
hetznercloud = "nixops_hetznercloud.plugin"

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
