name: CI
on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "**" ]

env:
  FLAKES_URL: https://github.com/numtide/nix-flakes-installer/releases/download/nix-3.0pre20200820_4d77513/install
  FLAKES_CONF: experimental-features = nix-command flakes

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
	with:
          # Nix Flakes doesn't work on shallow clones
          fetch-depth: 0
      - name: Nix
        uses: cachix/install-nix-action@v11
        with:
          install_url:      ${{env.FLAKES_URL}}
          extra_nix_config: ${{env.FLAKES_CONF}}
      - name: Build
        uses: cachix/install-nix-action@v11
      - run: nix flake check
  black:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Nix
        uses: cachix/install-nix-action@v11
      - name: Nix
        uses: cachix/install-nix-action@v11
        with:
          install_url:      ${{env.FLAKES_URL}}
          extra_nix_config: ${{env.FLAKES_CONF}}
      - name: Black
        run: 'nix-shell --run "black --check ."'
  flake8:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Nix
        uses: cachix/install-nix-action@v11
        with:
          install_url:      ${{env.FLAKES_URL}}
          extra_nix_config: ${{env.FLAKES_CONF}}
      - name: Flake8
        run: 'nix-shell --run "flake8 nixops_hetznercloud"'
  mypy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Nix
        uses: cachix/install-nix-action@v11
        with:
          install_url:      ${{env.FLAKES_URL}}
          extra_nix_config: ${{env.FLAKES_CONF}}
      - name: Mypy
        run: 'nix-shell --run "mypy nixops_hetznercloud"'
  parsing:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Nix
        uses: cachix/install-nix-action@v11
        with:
          install_url:      ${{env.FLAKES_URL}}
          extra_nix_config: ${{env.FLAKES_CONF}}
      - name: Parsing
        run: 'nix-shell --run "find . -name "*.nix" -exec nix-instantiate --parse --quiet {} >/dev/null +"'

