name: CI
on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "**" ]
jobs:
  parsing:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
      with:
        fetch-depth: 0
    - name: Nix
      uses: cachix/install-nix-action@v8
    - name: Cachix
      uses: cachix/cachix-action@v6
      with:
        name: nixops-hetznercloud
        signingKey: '${{ secrets.CACHIX_SIGNING_KEY }}'
    - name: Prefetch shell
      run: nix-shell --run true
    - name: Parsing
      run: './ci/check-nix-files.sh'
  build:
    runs-on: ubuntu-latest
    needs: parsing
    steps:
    - name: Checkout
      uses: actions/checkout@v2
      with:
        fetch-depth: 0
    - name: Nix
      uses: cachix/install-nix-action@v8
    - name: Cachix
      uses: cachix/cachix-action@v6
      with:
        name: nixops-hetznercloud
        signingKey: '${{ secrets.CACHIX_SIGNING_KEY }}'
    - run: nix-build
    - run: nix-shell --run true
  black:
    runs-on: ubuntu-latest
    needs: build
    steps:
    - name: Checkout
      uses: actions/checkout@v2
      with:
        fetch-depth: 0
    - name: Nix
      uses: cachix/install-nix-action@v8
    - name: Cachix
      uses: cachix/cachix-action@v6
      with:
        name: nixops-hetznercloud
        signingKey: '${{ secrets.CACHIX_SIGNING_KEY }}'
    - name: Prefetch shell
      run: nix-shell --run true
    - name: Black
      run: './ci/check-formatting.sh'
  flake8:
    runs-on: ubuntu-latest
    needs: build
    steps:
    - name: Checkout
      uses: actions/checkout@v2
      with:
        fetch-depth: 0
    - name: Nix
      uses: cachix/install-nix-action@v8
    - name: Cachix
      uses: cachix/cachix-action@v6
      with:
        name: nixops-hetznercloud
        signingKey: '${{ secrets.CACHIX_SIGNING_KEY }}'
    - name: Prefetch shell
      run: nix-shell --run true
    - name: Flake8
      run: './ci/check-flake8.sh'
  mypy:
    runs-on: ubuntu-latest
    needs: build
    steps:
    - name: Checkout
      uses: actions/checkout@v2
      with:
        fetch-depth: 0
    - name: Nix
      uses: cachix/install-nix-action@v8
    - name: Cachix
      uses: cachix/cachix-action@v6
      with:
        name: nixops-hetznercloud
        signingKey: '${{ secrets.CACHIX_SIGNING_KEY }}'
    - name: Prefetch shell
      run: nix-shell --run true
    - name: Mypy
      run: './ci/check-mypy.sh'
